// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	database "github.com/krobus00/iot-be/model/database"
	mock "github.com/stretchr/testify/mock"

	model "github.com/krobus00/krobot-building-block/model"

	sqlx "github.com/jmoiron/sqlx"

	testing "testing"
)

// NodeRepository is an autogenerated mock type for the NodeRepository type
type NodeRepository struct {
	mock.Mock
}

// FindNodeByID provides a mock function with given fields: ctx, db, input
func (_m *NodeRepository) FindNodeByID(ctx context.Context, db *sqlx.DB, input *database.Node) (*database.Node, error) {
	ret := _m.Called(ctx, db, input)

	var r0 *database.Node
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.DB, *database.Node) *database.Node); ok {
		r0 = rf(ctx, db, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.DB, *database.Node) error); ok {
		r1 = rf(ctx, db, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllNodes provides a mock function with given fields: ctx, db, paginationRequest, config
func (_m *NodeRepository) GetAllNodes(ctx context.Context, db *sqlx.DB, paginationRequest *model.PaginationRequest, config ...model.Config) ([]*database.Node, int64, error) {
	_va := make([]interface{}, len(config))
	for _i := range config {
		_va[_i] = config[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, db, paginationRequest)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*database.Node
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.DB, *model.PaginationRequest, ...model.Config) []*database.Node); ok {
		r0 = rf(ctx, db, paginationRequest, config...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*database.Node)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.DB, *model.PaginationRequest, ...model.Config) int64); ok {
		r1 = rf(ctx, db, paginationRequest, config...)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *sqlx.DB, *model.PaginationRequest, ...model.Config) error); ok {
		r2 = rf(ctx, db, paginationRequest, config...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetTableName provides a mock function with given fields:
func (_m *NodeRepository) GetTableName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Store provides a mock function with given fields: ctx, db, input
func (_m *NodeRepository) Store(ctx context.Context, db *sqlx.DB, input *database.Node) error {
	ret := _m.Called(ctx, db, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.DB, *database.Node) error); ok {
		r0 = rf(ctx, db, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNodeRepository creates a new instance of NodeRepository. It also registers a cleanup function to assert the mocks expectations.
func NewNodeRepository(t testing.TB) *NodeRepository {
	mock := &NodeRepository{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
